numpy

In [1]:
import numpy as np

Basic

In [2]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [3]:
b = np.array([[7.28, 28.7, 3.4], [20,28,7]])
print(b)

[[ 7.28 28.7   3.4 ]
 [20.   28.    7.  ]]


In [4]:
# get demension
print(a.ndim) 
print(b.ndim)

1
2


In [5]:
# get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [6]:
# get data type
print(a.dtype)
print(b.dtype)

int16
float64


In [7]:
# get each item size in Byte
print(a.itemsize)
print(b.itemsize)

2
8


In [8]:
# get array len
print(a.size)
print(b.size)

3
6


In [9]:
# get total size
print(a.nbytes)
print(b.nbytes)

6
48


Accessing / Changing specific elements, rows, columns, and ...

In [10]:
A = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [11]:
# get specific elements [r , c] | [r][c]
A[0,-1]

7

In [12]:
# get specific row [r , :]
A[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# get specific column [: , c]
A[:,1]

array([2, 9])

In [14]:
# get sub array [startindex:endindex:step, startindex:endindex:step]
A[0:2,0:7:2]

array([[ 1,  3,  5,  7],
       [ 8, 10, 12, 14]])

In [15]:
# set value to element
A[1,1] = 28
A

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8, 28, 10, 11, 12, 13, 14]])

In [16]:
# set mulitple values 1
A[0,:] = 7
A

array([[ 7,  7,  7,  7,  7,  7,  7],
       [ 8, 28, 10, 11, 12, 13, 14]])

In [17]:
# set multiple values 2
A[0,:] = [1,2,3,4,5,6,7]
A

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8, 28, 10, 11, 12, 13, 14]])

Initialzing different type of arrays

In [18]:
# all zeros 
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
# all ones
np.ones((2,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1]])

In [20]:
# all specific numbeers
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [21]:
# all specific number but instead of shape get another np.array and get that shape
np.full_like(A,28)

array([[28, 28, 28, 28, 28, 28, 28],
       [28, 28, 28, 28, 28, 28, 28]])

In [22]:
# random numbers
np.random.rand(3,3)

array([[0.25626605, 0.61654612, 0.38913184],
       [0.25633652, 0.29981075, 0.27692333],
       [0.37848998, 0.07667307, 0.81402689]])

In [23]:
# random integer 
np.random.randint(7,29 , size=(7,7))

array([[ 7, 19, 16, 22, 12, 15, 12],
       [19, 21, 13, 18, 14, 24, 25],
       [17, 16,  8,  9,  9, 25,  8],
       [27, 28, 26, 27, 21, 17, 16],
       [23, 11, 16, 13, 10,  9, 17],
       [16, 21, 23, 17,  7, 27,  7],
       [13, 14, 18,  7, 19, 26,  9]])

In [24]:
# i matrix
np.identity(3, dtype='int32')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Challange:
create 1 1 1 1 1
       1 0 0 0 1
       1 0 9 0 1
       1 0 0 0 1
       1 1 1 1 1 
without typing by hand

In [25]:
output = np.ones((5,5), dtype='int32')
output[1:-1,1:-1] = np.zeros((3,3),dtype='int32')
output[2,2] = 9
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


Mathmatics

In [26]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [27]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)
print(a ** 2)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]


In [28]:
print(np.sin(a))
print(np.cos(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


Linear algebra

In [29]:
a = np.ones((2,3))
b = np.full((3,4),2)

In [30]:
# matrix multiple
np.matmul(a,b)

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [31]:
# determinan of matrix
c = np.identity(3)
np.linalg.det(c)

1.0

statistics

In [32]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [33]:
np.min(a)

1

In [34]:
np.max(a)

8

In [35]:
np.sum(a)

36

Reorganizing arrays

In [36]:
# reshape
a = np.array([[1,2,3,4],[5,6,7,8]])
a.reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [38]:
# vertically stacking vector

v1 = np.array([1,2,3,4])
v2 = np.array([4,5,6,8])

np.vstack([v1,v2,v1])

array([[1, 2, 3, 4],
       [4, 5, 6, 8],
       [1, 2, 3, 4]])

In [42]:
# horizental stacking
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

Load data from file

In [44]:
file_data = np.genfromtxt('data.txt',delimiter=',')
file_data = file_data.astype('int32')

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

Boolean masking and advanced indexing

In [45]:
file_data > 20

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [48]:
file_data[file_data < 20]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19.])

In [61]:
file_data[[0,1,2],[1,3,4]]

array([ 2., 14., 25.])